name: PR checks
on:
  pull_request:
    branches:
      - master
permissions:
  contents: read
jobs:
  go-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - run: go test ./...
